// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ListCategoryController from "./list_category_controller"
application.register("list-category", ListCategoryController)

import ThreejsController from "./threejs_controller"
application.register("threejs", ThreejsController)
